### ISSUE TITLE
Show notes from teachers if they exist

### ISSUE THREAD

**Issue by andOrlando** [Aspine/aspine#312] opened 2021-10-18 13:49 UTC
In some cases teachers attatch notes to grades and it'd be pretty useful to show them iff they exist- as in we don't have a designated space for since it's not super common, but if there is a comment it'd be useful to have a little icon or something to see it. Not sure if this is already in the API from scrape.ts.

In some cases, this is a pretty key feature. At least for my AP Phys C, the comments are extreemly useful in thinking about and caculating my grade.

This could probably either be a modal or a tooltip. If it's a tooltip we can also rewrite the tooltip api a tad to include better style support

**Comment by psvenk** [comment] 2021-10-18 23:18
Is what you're describing the same as assignment feedback? I think this is already shown in the stats modal, but of course that only applies to assignments that have statistics. Fixing this situation is already being tracked in #167.

**Comment by jadebuckwalter** [comment] 2021-10-18 23:38
@andOrlando @psvenk I started working on adding assignment dates and feedback to assignments without statistics several months ago in #297 as part of the redesign for mobile, but I never pushed it to the main branch. The mobile redesign probably won't be done for a while, but I believe what is currently on the `mobile-assignments` is in a working state, so it might be a good idea to merge that now and work on the rest later. Thoughts?

**Comment by psvenk** [comment] 2021-10-18 23:42
@jadebuckwalter Let's continue this conversation in #297. I'm closing this issue because it seems to be a duplicate of #167.

**Closed as completed by psvenk** 2021-10-18 23:42 UTC
Labels: duplicate
